version: "3.5"

services:

  kong-database:
    container_name: kong-database
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong-pass
    ports:
      - "5432:5432"

  kong-migration:
    image: kong
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong-pass
    links:
      - kong-database
    depends_on:
      - kong-database

  kong-kong:
    container_name: kong-kong
    image: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong-pass
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    links:
      - kong-database
    depends_on:
      - kong-database
      - kong-migration
    ports:
      - 801:8000
    restart: always

  kong-konga:
    container_name: kong-konga
    image: pantsel/konga:latest
    depends_on:
      - kong-database
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_DATABASE: kong
      DB_USER: kong
      DB_PASSWORD: kong-pass
    restart: always
    ports:
      - 1337:1337
  
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    tty: true