version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: pass
     POSTGRES_DB: authDB
    ports:
     - '5432:5432'
    volumes:
     - data:/var/lib/pgsql/data
volumes:
  data:
